name: ecommerce_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'





#---packages----#

dependencies:
  flutter:
    sdk: flutter

  #---Utility packages----#


   

  
  #---Icons----# 
  cupertino_icons: ^1.0.6

#---end packages----#


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0





flutter:

  uses-material-design: true

  
  
  
  

#---Local Assets----#

assets:
  -assets/logos/
  -assets/icons/brands/
  -assets/images/

#---Local Fonts----#
fonts:
  -family: Poppins
  fonts:
      - asset: assests/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assests/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assests/fonts/Poppins-Italic.ttf
        style: italic
      - asset: assests/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assests/fonts/Poppins-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assests/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assests/fonts/Poppins-Bold.ttf
        weight: 800


  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
